

export const businessData = [
  {
    key: "1",
    id: 79843,
    logo: "public/assets/images/logo1.png",
    name: "SecuriToday",
    type: "Barber",
    plan: "BP",
    period: "Monthly",
    startDate: "18/09/2016",
    ExpiryDate: "18/09/2017",
    Status: "Active",
  },
  {
    key: "2",
    id: 397485,
    logo: "public/assets/images/logo2.png",
    name: "SiteDept",
    type: "Spa",
    plan: "SP",
    period: "Monthly",
    startDate: "15/08/2017",
    ExpiryDate: "18/09/2017",
    Status: "Expired",
  },
  {
    key: "3",
    id: 349753,
    logo: "public/assets/images/logo3.png",
    name: "Cloudrevel",
    type: "General",
    plan: "PP",
    period: "Yearly",
    startDate: "18/09/2016",
    ExpiryDate: "18/09/2017",
    Status: "Active",
  },
  {
    key: "4",
    id: 349875,
    logo: "public/assets/images/logo4.png",
    name: "Medicine",
    type: "Clinic",
    plan: "EP",
    period: "Monthly",
    startDate: "16/08/2013",
    ExpiryDate: "18/09/2017",
    Status: "Expired",
  },
  {
    key: "5",
    id: 379843,
    logo: "public/assets/images/logo5.png",
    name: "SecuriToday",
    type: "Barber",
    plan: "PP",
    period: "Yearly",
    startDate: "28/10/2012",
    ExpiryDate: "18/09/2017",
    Status: "Active",
  },
  {
    key: "6",
    id: 634753,
    logo: "public/assets/images/logo6.png",
    name: "Jumpsync",
    type: "Clinic",
    plan: "EP",
    period: "Monthly",
    startDate: "12/06/2020",
    ExpiryDate: "18/09/2017",
    Status: "Active",
  },
  {
    key: "7",
    id: 3948753,
    logo: "public/assets/images/logo7.png",
    name: "GameEight",
    type: "General",
    plan: "PP",
    period: "Yearly",
    startDate: "28/10/2012",
    ExpiryDate: "18/09/2017",
    Status: "Active",
  },
  {
    key: "8",
    id: 394,
    logo: "public/assets/images/logo8.png",
    name: "Excursy",
    type: "Clinic",
    plan: "EP",
    period: "Monthly",
    startDate: "28/10/2012",
    ExpiryDate: "18/09/2017",
    Status: "Expired",
  },
  {
    key: "9",
    id: 349857,
    logo: "public/assets/images/logo9.png",
    name: "Seekingon",
    type: "Barber",
    plan: "BP",
    period: "Yearly",
    startDate: "16/08/2013",
    ExpiryDate: "18/09/2017",
    Status: "Active",
  },
  {
    key: "10",
    id: 349875,
    logo: "public/assets/images/logo10.png",
    name: "QuickSpace",
    type: "Spa",
    plan: "EP",
    period: "Monthly",
    startDate: "07/05/2016",
    ExpiryDate: "18/09/2017",
    Status: "Expired",
  },
];
