export * from './Dashboard'
export * from './AllBusinessPage'
export * from './CustomersPage'
export * from './BookingPage'
export * from './RevenuePage'
export * from './DemoRequestPage'
export * from './StaffPage'
export * from './SubscriptionPlanPage'
export * from './SubscriptionManagementPage'
export * from './DiscountPage'
export * from './TermsConditionPage'
export * from './FaqsPage'
export * from './PrivacyPolicyPage'
export * from './SettingsPage'
export * from './ActivityLogPage'

export * from './Sidebar'
export * from './LoginPage'
export * from './ForgotPassword'

